// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "Kennedy Loud Cannabis",
  domain: "kennedyloudcannabis.com",
  city: "Brampton",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-brampton",
  address: "49 Hillcrest Ave, Unit 104, Brampton, ON L6W 1Y7",
  streetAddress: "49 Hillcrest Ave, Unit 104",
  postalCode: "L6W 1Y7",
  phone: "(437) 237-2286",
  phoneIntl: "+14372372286",
  neighborhood: "Kennedy Road / Brampton",
  nearbyAreas: ["Kennedy Road", "Downtown Brampton", "Queen Street", "Main Street", "Brampton", "Peel Region", "Brampton Transit", "Bramalea"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "https://maps.google.com/?q=49+Hillcrest+Ave,+Unit+104,+Brampton,+ON+L6W+1Y7",
  mapEmbedUrl: "https://maps.google.com/maps?q=49%20Hillcrest%20Ave%2C%20Unit%20104%2C%20Brampton%2C%20ON%20L6W%201Y7&t=&z=15&ie=UTF8&iwloc=&output=embed",
  latitude: "43.6894",
  longitude: "-79.7516",
  hours: ["Open 24 Hours"],
  seoTitle: "Kennedy Loud Cannabis | Weed Dispensary in Brampton",
  metaDescription: "Kennedy Loud Cannabis is a local weed dispensary in Brampton offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Kennedy Road", "Downtown Brampton", "Queen Street"],
  introVariant: "Welcome to Kennedy Loud Cannabis, your premier weed dispensary in Brampton situated right on 49 Hillcrest Ave, Unit 104. We are dedicated to providing adults 19+ with top-tier weed, premium cannabis flower, pre-rolls, edibles, THC vapes, concentrates, and CBD products. If you are looking for a trusted cannabis store near Kennedy Road / Brampton or a weed shop near Downtown Brampton, stop by today to consult with our knowledgeable staff.",
  neighborhoodDescription: "Located in the vibrant Kennedy Road / Brampton district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Dedicated customer parking is available directly on-site",
  transitNote: "Conveniently accessible via Brampton Transit routes serving Kennedy Road.",
  sectionTitle: "Serving Customers Near Kennedy Road and Brampton"
};
