export const gbpLocation = {
  storeName: "Kennedy Loud Cannabis",
  domain: "kennedyloudcannabis.com",
  city: "Brampton",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-brampton",
  address: "49 Hillcrest Ave, Unit 104, Brampton, ON L6W 1Y7",
  streetAddress: "49 Hillcrest Ave, Unit 104",
  postalCode: "L6W 1Y7",
  phone: "+1 (289) 206-1181",
  phoneIntl: "+12892061181",
  neighborhood: "Kennedy Road / Brampton",
  nearbyAreas: ["Kennedy Road", "Downtown Brampton", "Queen Street", "Main Street", "Brampton", "Brampton Transit", "Bramalea"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "",
  mapEmbedUrl: "",
  latitude: "43.6940006",
  longitude: "-79.7477885",
  hours: ["Open 24 Hours"],
  seoTitle: "Kennedy Road Brampton Dispensary | Kennedy Loud Cannabis 24/7",
  metaDescription: "Walk-in Brampton dispensary at 49 Hillcrest Ave Unit 104, near Kennedy Rd. Open 24/7. Flower from $3/g. Call (289) 206-1181. Adults 19+.",
  localLandmarks: ["Kennedy Road", "Downtown Brampton", "Queen Street"],
  introVariant: "Kennedy Loud Cannabis is the walk-in Brampton dispensary at 49 Hillcrest Avenue, Unit 104. The store sits on the Kennedy Road corridor and serves Hillcrest, Kennedy, and the blocks feeding Downtown Brampton from the south and east.",
  neighborhoodDescription: "Kennedy Loud Cannabis is located near Hillcrest Ave and Kennedy Road in Brampton.",
  parkingNote: "Check the current map listing, posted signs, or contact the store for parking details before visiting.",
  transitNote: "Check the current map listing or Brampton Transit information before visiting by transit.",
  sectionTitle: "Brampton Weed Dispensary on the Kennedy Road Corridor"
};
